name: sphere
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at ht tps://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.17.3 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  auto_route: ^4.0.1
  bloc: ^8.0.3
  cached_network_image: ^3.2.1
  connectivity_plus: ^2.3.4
  cupertino_icons: ^1.0.5
  device_info_plus: ^3.2.4
  dio: ^4.0.6
  easy_localization: ^3.0.1
  equatable: ^2.0.3
  fast_immutable_collections: ^7.4.1
  flutter_dotenv: ^5.0.2
  flutter_image_compress: ^1.1.0
  flutter_slidable: ^1.3.0
  expandable: ^5.0.1
  flutter_svg: ^1.1.0
  flutter_typeahead: ^4.0.0
  freezed_annotation: ^2.0.3
  get: ^4.6.5
  get_it: ^7.2.0
  google_sign_in: ^5.3.3
  group_button: ^5.0.1
  image_picker: ^0.8.5+3
  injectable: ^1.5.3
  json_annotation: ^4.5.0
  local_auth: ^2.1.0
  logger: ^1.1.0
  overlay_support: ^2.0.1
  package_info_plus: ^1.4.2
  pin_code_fields: ^7.4.0
  retrofit: ^3.0.1+1
  rxdart: ^0.27.4
  simple_rich_text: ^2.0.49
  step_progress_indicator: ^1.0.2
  given_when_then_unit_test: ^0.1.0
  shouldly: ^0.5.0+1
  percent_indicator: ^4.2.2
  meta: ^1.7.0
  path: ^1.8.1
  tuna_flutter_range_slider: ^1.0.0
  flutter_inset_box_shadow: ^1.0.8
  shared_preferences: ^2.0.15
  vfx_flutter_common:
#    path: ../vfx_flutter_common
    git:
      url: https://gitlab.com/frostyland/vfx_flutter_common.git
      ref: torexo


dev_dependencies:
  flutter_test:
    sdk: flutter
  auto_route_generator: ^4.0.0
  build_runner: ^2.1.11
  flutter_lints: ^2.0.1
  freezed: ^2.0.3+1
  injectable_generator: ^1.5.3
  json_serializable: ^6.2.0
  mocktail: ^0.3.0
  retrofit_generator: ^4.0.1

#dependency_overrides:
#  analyzer: ^3.0.0

# The following section is specific to Flutter.
flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/translations/

  fonts:
    - family: Netflix
      fonts:
        - asset: fonts/netflix_sans/NetflixSansBlack.ttf
          weight: 900
        - asset: fonts/netflix_sans/NetflixSansBold.ttf
          weight: 700
        - asset: fonts/netflix_sans/NetflixSansMedium.ttf
          weight: 500
        - asset: fonts/netflix_sans/NetflixSansRegular.ttf
          weight: 400
        - asset: fonts/netflix_sans/NetflixSansLight.ttf
          weight: 200
        - asset: fonts/netflix_sans/NetflixSansThin.ttf
          weight: 100
